---

 - name: Creating helsinki directory
   file: path=/usr/local/helsinki state=directory

 - name: copy reindex.sh
   copy: src=reindex.sh dest=/usr/local/helsinki/reindex.sh
         owner=root group=root mode=0700

 - name: copy mailshot.sh
   copy: src=mailshot.sh dest=/usr/local/helsinki/mailshot.sh
         owner=root group=root mode=0700

 - cron: name="helsinki reindex" job="/usr/local/helsinki/reindex.sh" minute=0 hour=0

 - cron: name="helsinki mailshot"  job="/usr/local/helsinki/mailshot.sh" minute=0 hour=7
